import re
import os
from pathlib import Path
from typing import Dict, Any, List, Optional
import logging

logger = logging.getLogger("app.agent.document_workflow.validator")


class SemanticContentValidator:
    """
    Semantic validator that runs BEFORE Sandbox execution.
    Verifies Scope Lock (Must Include, Must Not Include), detects placeholders,
    and checks completeness and structural consistency.
    """

    PLACEHOLDER_PATTERN = re.compile(
        r"(\[insert[^\]]*\]|lorem ipsum|todo\b|tbd\b|<placeholder>|\bexample text\b)",
        re.IGNORECASE
    )

    @classmethod
    def validate(
        cls,
        integrated_content: Dict[str, Any],
        scope_lock: Dict[str, Any],
        query: str = ""
    ) -> Dict[str, Any]:
        issues: List[Dict[str, Any]] = []

        if not isinstance(scope_lock, dict):
            scope_lock = {"must_include": [], "must_not_include": []}
        if not isinstance(integrated_content, dict):
            integrated_content = {"sections": [{"heading": "Summary", "paragraphs": [str(integrated_content)]}]}

        must_include = scope_lock.get("must_include", [])
        must_not_include = scope_lock.get("must_not_include", [])

        sections = integrated_content.get("sections") or []
        data_table = integrated_content.get("data_table")
        all_text_blobs = []

        # 1. Structure check: at least 1 section or data_table must exist
        if not sections and not data_table:
            issues.append({
                "type": "EMPTY_DOCUMENT",
                "section_id": "all",
                "message": "Document contains neither sections nor data table.",
            })

        # 2. Iterate sections to check placeholders and forbidden content
        for idx, sec in enumerate(sections):
            if isinstance(sec, str):
                heading = sec
                paragraphs = []
                bullet_points = []
            elif isinstance(sec, dict):
                heading = sec.get("heading", f"Section_{idx + 1}")
                paragraphs = sec.get("paragraphs", [])
                bullet_points = sec.get("bullet_points", [])
            else:
                heading = str(sec)
                paragraphs = []
                bullet_points = []

            sec_id = f"section_{idx + 1}"
            sec_texts = [heading] + paragraphs + bullet_points

            for text in sec_texts:
                all_text_blobs.append(text)

                # Check placeholders
                ph_match = cls.PLACEHOLDER_PATTERN.search(text)
                if ph_match:
                    issues.append({
                        "type": "PLACEHOLDER_DETECTED",
                        "section_id": sec_id,
                        "message": f"Placeholder token '{ph_match.group(0)}' found in section '{heading}'.",
                    })

                # Check forbidden items (MUST NOT INCLUDE)
                for forbidden in must_not_include:
                    if forbidden.lower() in text.lower():
                        issues.append({
                            "type": "FORBIDDEN_CONTENT_DETECTED",
                            "section_id": sec_id,
                            "message": f"Forbidden item '{forbidden}' was detected in section '{heading}'.",
                        })

        full_doc_text = " ".join(all_text_blobs).lower()

        # 3. Completeness check: MUST INCLUDE items must appear
        for must_item in must_include:
            # Skip broad query strings if words are present
            must_keywords = [w.lower() for w in must_item.split() if len(w) > 3 and w.lower() not in ["create", "generate", "document", "file"]]
            if must_keywords and not any(kw in full_doc_text for kw in must_keywords):
                issues.append({
                    "type": "MISSING_REQUIRED_CONTENT",
                    "section_id": "all",
                    "message": f"Explicitly required topic/content '{must_item}' is missing from document text.",
                })

        is_valid = len(issues) == 0
        logger.info(f"Semantic validation complete: valid={is_valid}, {len(issues)} issue(s).")
        return {
            "valid": is_valid,
            "issues": issues,
            "checked_sections": len(sections),
            "checked_must_includes": len(must_include),
            "checked_forbiddens": len(must_not_include),
        }


class ArtifactValidator:
    """
    Validates the actual file output generated by the Sandbox.
    Ensures format correctness, non-empty content, and uncorrupted file structure.
    """

    @staticmethod
    def validate_file(target_path: Path, expected_format: str, min_size_bytes: int = 50) -> Dict[str, Any]:
        target = Path(target_path)
        errors: List[str] = []

        if not target.exists():
            return {
                "valid": False,
                "format": expected_format,
                "path": str(target),
                "errors": [f"File does not exist: {target.name}"],
            }

        size = target.stat().st_size
        if size < min_size_bytes:
            errors.append(f"File is unexpectedly small ({size} bytes).")

        fmt = expected_format.lower().lstrip(".")

        try:
            if fmt == "docx":
                from docx import Document
                doc = Document(str(target))
                text_len = sum(len(p.text.strip()) for p in doc.paragraphs)
                if text_len == 0 and len(doc.tables) == 0:
                    errors.append("DOCX contains zero readable paragraphs or tables.")

            elif fmt == "xlsx":
                import openpyxl
                wb = openpyxl.load_workbook(str(target), read_only=True)
                if not wb.sheetnames:
                    errors.append("XLSX contains no worksheets.")
                wb.close()

            elif fmt == "pptx":
                from pptx import Presentation
                prs = Presentation(str(target))
                if len(prs.slides) == 0:
                    errors.append("PPTX contains no slides.")

            elif fmt == "pdf":
                with open(target, "rb") as f:
                    header = f.read(5)
                if not header.startswith(b"%PDF"):
                    errors.append("PDF does not start with valid %PDF header.")

            elif fmt in ["csv", "txt", "md"]:
                text = target.read_text(encoding="utf-8", errors="ignore")
                if not text.strip():
                    errors.append(f"{fmt.upper()} file is empty.")

        except Exception as e:
            errors.append(f"Technical validation failure for {fmt.upper()}: {str(e)}")

        is_valid = len(errors) == 0
        logger.info(f"Artifact validation for {target.name}: valid={is_valid}")
        return {
            "valid": is_valid,
            "format": fmt,
            "path": str(target),
            "size": size,
            "errors": errors,
        }
