[project]
name = "backend"
version = "0.1.0"
description = "Shield AI Backend API Service"
readme = "README.md"
authors = [
    { name = "saurabh-yadav-ggu", email = "saurabhjlpyadav@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "bcrypt",
    "pyjwt",
    "pydantic",
    "pydantic-settings",
    "email-validator",
    "langchain",
    "langchain-core",
    "langchain-community",
    "langchain-ollama",
    "langchain-chroma",
    "langchain-text-splitters",
    "langchain-mcp-adapters",
    "mcp-docgen",
    "langgraph",
    "pypdf",
    "python-dotenv",
    "requests",
    "langgraph-checkpoint-sqlite>=3.1.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
